title:             [Cristiano Pimentel]
email:             cristiano.pimentel@hotmail.com
description:       A web version of Cristiano Pimentel
author:            Cristiano Pimentel
baseurl:           ""
url:               "http://cris.live"

# Social Profiles
linkedin_username: cpimentel
github_username:   cristianopimentel

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
