# Site settings
title: [cristianopimentel]
header-img: img/home-bg.jpg
email: cristiano.pimentel@hotmail.com
copyright_name: Cristiano Pimentel
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: 
github_username:  cristianopimentel
facebook_username:  cristiano.pimentel
email_username:  cristiano.pimentel@hotmail.com
deezer_profile: 843652197  
trello_username: cpimentel
skype: cristiano.pimentel

# Paginator
paginate_path: "blog/page:num"

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
