# Site settings
title: [Cristiano Pimentel]
header-img: img/default.png
email: cristiano.pimentel@hotmail.com
copyright_name: Cristiano Pimentel
description: "I'm a Trust builder and Code Crafstman Software Engineer. Trust is the ultimate feedback!"
baseurl: ""
url: "http://cristianopimentel.live"

profile_name: Cristiano Pimentel
profile_title: Software Engineer
profile_image: img/profile.jpg

twitter_username: 
github_username:  cristianopimentel
facebook_username:  cristiano.pimentel
email_username:  cristiano.pimentel@hotmail.com
trello_username: cpimentel
skype: cristiano.pimentel

# Paginator
paginate_path: "blog/page:num"

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
